name: Dependabot Jira

on:
  pull_request:
    types:
      - opened
    branches:
      - master
  workflow_dispatch:
 #   inputs:
 #     message:
 #       description: 'Aakash is triggering workflow manually'
 #       required: true    

env:
  JIRA_BASE_URL: https://cruzeaakash.atlassian.net/
  JIRA_USER_EMAIL: aakash.shinghal1993@gmail.com
  JIRA_API_TOKEN: ${{ secrets.JiraApiToken }}
  JIRA_PROJECT: STOC
  JIRA_ISSUE_TYPE: Bug

jobs:
  create_jira:
    name: Dependabot Jira
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JiraApiToken }}

    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v2.0.1
      with:
        project: ${{ env.JIRA_PROJECT }}
        issuetype: ${{ env.JIRA_ISSUE_TYPE }}
        summary: |
          [${{github.event.repository.name }}] ${{github.event.pull_request.title }}
        description: |
          ${{github.event.pull_request.html_url }}
